[SANSGB2.gaster_blaster_2_0]
path = "sprites/sans/gaster_blaster_2"

[SANSGB2.gaster_blaster_2_1]
path = "sprites/sans/gaster_blaster_2"
rotation = 18

[SANSGB2.gaster_blaster_2_2]
path = "sprites/sans/gaster_blaster_2"
rotation = 36

[SANSGB2.gaster_blaster_2_3]
path = "sprites/sans/gaster_blaster_2"
rotation = 54

[SANSGB2.gaster_blaster_2_4]
path = "sprites/sans/gaster_blaster_2"
rotation = 72

[SANSGB2.gaster_blaster_2_5]
path = "sprites/sans/gaster_blaster_2"
rotation = 90

[SANSGB2.gaster_blaster_2_6]
path = "sprites/sans/gaster_blaster_2"
rotation = 108

[SANSGB2.gaster_blaster_2_7]
path = "sprites/sans/gaster_blaster_2"
rotation = 126

[SANSGB2.gaster_blaster_2_8]
path = "sprites/sans/gaster_blaster_2"
rotation = 144

[SANSGB2.gaster_blaster_2_9]
path = "sprites/sans/gaster_blaster_2"
rotation = 162

[SANSGB2.gaster_blaster_2_10]
path = "sprites/sans/gaster_blaster_2"
rotation = 180

[SANSGB2.gaster_blaster_2_11]
path = "sprites/sans/gaster_blaster_2"
rotation = 198

[SANSGB2.gaster_blaster_2_12]
path = "sprites/sans/gaster_blaster_2"
rotation = 216

[SANSGB2.gaster_blaster_2_13]
path = "sprites/sans/gaster_blaster_2"
rotation = 234

[SANSGB2.gaster_blaster_2_14]
path = "sprites/sans/gaster_blaster_2"
rotation = 252

[SANSGB2.gaster_blaster_2_15]
path = "sprites/sans/gaster_blaster_2"
rotation = 270

[SANSGB2.gaster_blaster_2_16]
path = "sprites/sans/gaster_blaster_2"
rotation = 288

[SANSGB2.gaster_blaster_2_17]
path = "sprites/sans/gaster_blaster_2"
rotation = 306

[SANSGB2.gaster_blaster_2_18]
path = "sprites/sans/gaster_blaster_2"
rotation = 324

[SANSGB2.gaster_blaster_2_19]
path = "sprites/sans/gaster_blaster_2"
rotation = 342
