[SANSGB1.gaster_blaster_1_0]
path = "sprites/sans/gaster_blaster_1"

[SANSGB1.gaster_blaster_1_1]
path = "sprites/sans/gaster_blaster_1"
rotation = 18

[SANSGB1.gaster_blaster_1_2]
path = "sprites/sans/gaster_blaster_1"
rotation = 36

[SANSGB1.gaster_blaster_1_3]
path = "sprites/sans/gaster_blaster_1"
rotation = 54

[SANSGB1.gaster_blaster_1_4]
path = "sprites/sans/gaster_blaster_1"
rotation = 72

[SANSGB1.gaster_blaster_1_5]
path = "sprites/sans/gaster_blaster_1"
rotation = 90

[SANSGB1.gaster_blaster_1_6]
path = "sprites/sans/gaster_blaster_1"
rotation = 108

[SANSGB1.gaster_blaster_1_7]
path = "sprites/sans/gaster_blaster_1"
rotation = 126

[SANSGB1.gaster_blaster_1_8]
path = "sprites/sans/gaster_blaster_1"
rotation = 144

[SANSGB1.gaster_blaster_1_9]
path = "sprites/sans/gaster_blaster_1"
rotation = 162

[SANSGB1.gaster_blaster_1_10]
path = "sprites/sans/gaster_blaster_1"
rotation = 180

[SANSGB1.gaster_blaster_1_11]
path = "sprites/sans/gaster_blaster_1"
rotation = 198

[SANSGB1.gaster_blaster_1_12]
path = "sprites/sans/gaster_blaster_1"
rotation = 216

[SANSGB1.gaster_blaster_1_13]
path = "sprites/sans/gaster_blaster_1"
rotation = 234

[SANSGB1.gaster_blaster_1_14]
path = "sprites/sans/gaster_blaster_1"
rotation = 252

[SANSGB1.gaster_blaster_1_15]
path = "sprites/sans/gaster_blaster_1"
rotation = 270

[SANSGB1.gaster_blaster_1_16]
path = "sprites/sans/gaster_blaster_1"
rotation = 288

[SANSGB1.gaster_blaster_1_17]
path = "sprites/sans/gaster_blaster_1"
rotation = 306

[SANSGB1.gaster_blaster_1_18]
path = "sprites/sans/gaster_blaster_1"
rotation = 324

[SANSGB1.gaster_blaster_1_19]
path = "sprites/sans/gaster_blaster_1"
rotation = 342
