[encoding]
format = "run_length"

[sprites.gaster_blaster_5_00]
path = "sprites/gaster_blaster_5"

[sprites.gaster_blaster_5_01]
path = "sprites/gaster_blaster_5"
rotation = 18

[sprites.gaster_blaster_5_02]
path = "sprites/gaster_blaster_5"
rotation = 36

[sprites.gaster_blaster_5_03]
path = "sprites/gaster_blaster_5"
rotation = 54

[sprites.gaster_blaster_5_04]
path = "sprites/gaster_blaster_5"
rotation = 72

[sprites.gaster_blaster_5_05]
path = "sprites/gaster_blaster_5"
rotation = 90

[sprites.gaster_blaster_5_06]
path = "sprites/gaster_blaster_5"
rotation = 108

[sprites.gaster_blaster_5_07]
path = "sprites/gaster_blaster_5"
rotation = 126

[sprites.gaster_blaster_5_08]
path = "sprites/gaster_blaster_5"
rotation = 144

[sprites.gaster_blaster_5_09]
path = "sprites/gaster_blaster_5"
rotation = 162

[sprites.gaster_blaster_5_10]
path = "sprites/gaster_blaster_5"
rotation = 180

[sprites.gaster_blaster_5_11]
path = "sprites/gaster_blaster_5"
rotation = 198

[sprites.gaster_blaster_5_12]
path = "sprites/gaster_blaster_5"
rotation = 216

[sprites.gaster_blaster_5_13]
path = "sprites/gaster_blaster_5"
rotation = 234

[sprites.gaster_blaster_5_14]
path = "sprites/gaster_blaster_5"
rotation = 252

[sprites.gaster_blaster_5_15]
path = "sprites/gaster_blaster_5"
rotation = 270

[sprites.gaster_blaster_5_16]
path = "sprites/gaster_blaster_5"
rotation = 288

[sprites.gaster_blaster_5_17]
path = "sprites/gaster_blaster_5"
rotation = 306

[sprites.gaster_blaster_5_18]
path = "sprites/gaster_blaster_5"
rotation = 324

[sprites.gaster_blaster_5_19]
path = "sprites/gaster_blaster_5"
rotation = 342
