[SANSGB0.gaster_blaster_0_0]
path = "sprites/sans/gaster_blaster_0"

[SANSGB0.gaster_blaster_0_1]
path = "sprites/sans/gaster_blaster_0"
rotation = 18

[SANSGB0.gaster_blaster_0_2]
path = "sprites/sans/gaster_blaster_0"
rotation = 36

[SANSGB0.gaster_blaster_0_3]
path = "sprites/sans/gaster_blaster_0"
rotation = 54

[SANSGB0.gaster_blaster_0_4]
path = "sprites/sans/gaster_blaster_0"
rotation = 72

[SANSGB0.gaster_blaster_0_5]
path = "sprites/sans/gaster_blaster_0"
rotation = 90

[SANSGB0.gaster_blaster_0_6]
path = "sprites/sans/gaster_blaster_0"
rotation = 108

[SANSGB0.gaster_blaster_0_7]
path = "sprites/sans/gaster_blaster_0"
rotation = 126

[SANSGB0.gaster_blaster_0_8]
path = "sprites/sans/gaster_blaster_0"
rotation = 144

[SANSGB0.gaster_blaster_0_9]
path = "sprites/sans/gaster_blaster_0"
rotation = 162

[SANSGB0.gaster_blaster_0_10]
path = "sprites/sans/gaster_blaster_0"
rotation = 180

[SANSGB0.gaster_blaster_0_11]
path = "sprites/sans/gaster_blaster_0"
rotation = 198

[SANSGB0.gaster_blaster_0_12]
path = "sprites/sans/gaster_blaster_0"
rotation = 216

[SANSGB0.gaster_blaster_0_13]
path = "sprites/sans/gaster_blaster_0"
rotation = 234

[SANSGB0.gaster_blaster_0_14]
path = "sprites/sans/gaster_blaster_0"
rotation = 252

[SANSGB0.gaster_blaster_0_15]
path = "sprites/sans/gaster_blaster_0"
rotation = 270

[SANSGB0.gaster_blaster_0_16]
path = "sprites/sans/gaster_blaster_0"
rotation = 288

[SANSGB0.gaster_blaster_0_17]
path = "sprites/sans/gaster_blaster_0"
rotation = 306

[SANSGB0.gaster_blaster_0_18]
path = "sprites/sans/gaster_blaster_0"
rotation = 324

[SANSGB0.gaster_blaster_0_19]
path = "sprites/sans/gaster_blaster_0"
rotation = 342
