[encoding]
format = "run_length"

[sprites.gaster_blaster_0_00]
path = "sprites/gaster_blaster_0"

[sprites.gaster_blaster_0_01]
path = "sprites/gaster_blaster_0"
rotation = 18

[sprites.gaster_blaster_0_02]
path = "sprites/gaster_blaster_0"
rotation = 36

[sprites.gaster_blaster_0_03]
path = "sprites/gaster_blaster_0"
rotation = 54

[sprites.gaster_blaster_0_04]
path = "sprites/gaster_blaster_0"
rotation = 72

[sprites.gaster_blaster_0_05]
path = "sprites/gaster_blaster_0"
rotation = 90

[sprites.gaster_blaster_0_06]
path = "sprites/gaster_blaster_0"
rotation = 108

[sprites.gaster_blaster_0_07]
path = "sprites/gaster_blaster_0"
rotation = 126

[sprites.gaster_blaster_0_08]
path = "sprites/gaster_blaster_0"
rotation = 144

[sprites.gaster_blaster_0_09]
path = "sprites/gaster_blaster_0"
rotation = 162

[sprites.gaster_blaster_0_10]
path = "sprites/gaster_blaster_0"
rotation = 180

[sprites.gaster_blaster_0_11]
path = "sprites/gaster_blaster_0"
rotation = 198

[sprites.gaster_blaster_0_12]
path = "sprites/gaster_blaster_0"
rotation = 216

[sprites.gaster_blaster_0_13]
path = "sprites/gaster_blaster_0"
rotation = 234

[sprites.gaster_blaster_0_14]
path = "sprites/gaster_blaster_0"
rotation = 252

[sprites.gaster_blaster_0_15]
path = "sprites/gaster_blaster_0"
rotation = 270

[sprites.gaster_blaster_0_16]
path = "sprites/gaster_blaster_0"
rotation = 288

[sprites.gaster_blaster_0_17]
path = "sprites/gaster_blaster_0"
rotation = 306

[sprites.gaster_blaster_0_18]
path = "sprites/gaster_blaster_0"
rotation = 324

[sprites.gaster_blaster_0_19]
path = "sprites/gaster_blaster_0"
rotation = 342
