[gaster_blaster_0.gaster_blaster_0_0]
path = "sprites/sans/gaster_blaster_0"

[gaster_blaster_0.gaster_blaster_0_1]
path = "sprites/sans/gaster_blaster_0"
rotation = 18

[gaster_blaster_0.gaster_blaster_0_2]
path = "sprites/sans/gaster_blaster_0"
rotation = 36

[gaster_blaster_0.gaster_blaster_0_3]
path = "sprites/sans/gaster_blaster_0"
rotation = 54

[gaster_blaster_0.gaster_blaster_0_4]
path = "sprites/sans/gaster_blaster_0"
rotation = 72

[gaster_blaster_0.gaster_blaster_0_5]
path = "sprites/sans/gaster_blaster_0"
rotation = 90

[gaster_blaster_0.gaster_blaster_0_6]
path = "sprites/sans/gaster_blaster_0"
rotation = 108

[gaster_blaster_0.gaster_blaster_0_7]
path = "sprites/sans/gaster_blaster_0"
rotation = 126

[gaster_blaster_0.gaster_blaster_0_8]
path = "sprites/sans/gaster_blaster_0"
rotation = 144

[gaster_blaster_0.gaster_blaster_0_9]
path = "sprites/sans/gaster_blaster_0"
rotation = 162

[gaster_blaster_0.gaster_blaster_0_10]
path = "sprites/sans/gaster_blaster_0"
rotation = 180

[gaster_blaster_0.gaster_blaster_0_11]
path = "sprites/sans/gaster_blaster_0"
rotation = 198

[gaster_blaster_0.gaster_blaster_0_12]
path = "sprites/sans/gaster_blaster_0"
rotation = 216

[gaster_blaster_0.gaster_blaster_0_13]
path = "sprites/sans/gaster_blaster_0"
rotation = 234

[gaster_blaster_0.gaster_blaster_0_14]
path = "sprites/sans/gaster_blaster_0"
rotation = 252

[gaster_blaster_0.gaster_blaster_0_15]
path = "sprites/sans/gaster_blaster_0"
rotation = 270

[gaster_blaster_0.gaster_blaster_0_16]
path = "sprites/sans/gaster_blaster_0"
rotation = 288

[gaster_blaster_0.gaster_blaster_0_17]
path = "sprites/sans/gaster_blaster_0"
rotation = 306

[gaster_blaster_0.gaster_blaster_0_18]
path = "sprites/sans/gaster_blaster_0"
rotation = 324

[gaster_blaster_0.gaster_blaster_0_19]
path = "sprites/sans/gaster_blaster_0"
rotation = 342

[gaster_blaster_1.gaster_blaster_1_0]
path = "sprites/sans/gaster_blaster_1"

[gaster_blaster_1.gaster_blaster_1_1]
path = "sprites/sans/gaster_blaster_1"
rotation = 18

[gaster_blaster_1.gaster_blaster_1_2]
path = "sprites/sans/gaster_blaster_1"
rotation = 36

[gaster_blaster_1.gaster_blaster_1_3]
path = "sprites/sans/gaster_blaster_1"
rotation = 54

[gaster_blaster_1.gaster_blaster_1_4]
path = "sprites/sans/gaster_blaster_1"
rotation = 72

[gaster_blaster_1.gaster_blaster_1_5]
path = "sprites/sans/gaster_blaster_1"
rotation = 90

[gaster_blaster_1.gaster_blaster_1_6]
path = "sprites/sans/gaster_blaster_1"
rotation = 108

[gaster_blaster_1.gaster_blaster_1_7]
path = "sprites/sans/gaster_blaster_1"
rotation = 126

[gaster_blaster_1.gaster_blaster_1_8]
path = "sprites/sans/gaster_blaster_1"
rotation = 144

[gaster_blaster_1.gaster_blaster_1_9]
path = "sprites/sans/gaster_blaster_1"
rotation = 162

[gaster_blaster_1.gaster_blaster_1_10]
path = "sprites/sans/gaster_blaster_1"
rotation = 180

[gaster_blaster_1.gaster_blaster_1_11]
path = "sprites/sans/gaster_blaster_1"
rotation = 198

[gaster_blaster_1.gaster_blaster_1_12]
path = "sprites/sans/gaster_blaster_1"
rotation = 216

[gaster_blaster_1.gaster_blaster_1_13]
path = "sprites/sans/gaster_blaster_1"
rotation = 234

[gaster_blaster_1.gaster_blaster_1_14]
path = "sprites/sans/gaster_blaster_1"
rotation = 252

[gaster_blaster_1.gaster_blaster_1_15]
path = "sprites/sans/gaster_blaster_1"
rotation = 270

[gaster_blaster_1.gaster_blaster_1_16]
path = "sprites/sans/gaster_blaster_1"
rotation = 288

[gaster_blaster_1.gaster_blaster_1_17]
path = "sprites/sans/gaster_blaster_1"
rotation = 306

[gaster_blaster_1.gaster_blaster_1_18]
path = "sprites/sans/gaster_blaster_1"
rotation = 324

[gaster_blaster_1.gaster_blaster_1_19]
path = "sprites/sans/gaster_blaster_1"
rotation = 342

[gaster_blaster_2.gaster_blaster_2_0]
path = "sprites/sans/gaster_blaster_2"

[gaster_blaster_2.gaster_blaster_2_1]
path = "sprites/sans/gaster_blaster_2"
rotation = 18

[gaster_blaster_2.gaster_blaster_2_2]
path = "sprites/sans/gaster_blaster_2"
rotation = 36

[gaster_blaster_2.gaster_blaster_2_3]
path = "sprites/sans/gaster_blaster_2"
rotation = 54

[gaster_blaster_2.gaster_blaster_2_4]
path = "sprites/sans/gaster_blaster_2"
rotation = 72

[gaster_blaster_2.gaster_blaster_2_5]
path = "sprites/sans/gaster_blaster_2"
rotation = 90

[gaster_blaster_2.gaster_blaster_2_6]
path = "sprites/sans/gaster_blaster_2"
rotation = 108

[gaster_blaster_2.gaster_blaster_2_7]
path = "sprites/sans/gaster_blaster_2"
rotation = 126

[gaster_blaster_2.gaster_blaster_2_8]
path = "sprites/sans/gaster_blaster_2"
rotation = 144

[gaster_blaster_2.gaster_blaster_2_9]
path = "sprites/sans/gaster_blaster_2"
rotation = 162

[gaster_blaster_2.gaster_blaster_2_10]
path = "sprites/sans/gaster_blaster_2"
rotation = 180

[gaster_blaster_2.gaster_blaster_2_11]
path = "sprites/sans/gaster_blaster_2"
rotation = 198

[gaster_blaster_2.gaster_blaster_2_12]
path = "sprites/sans/gaster_blaster_2"
rotation = 216

[gaster_blaster_2.gaster_blaster_2_13]
path = "sprites/sans/gaster_blaster_2"
rotation = 234

[gaster_blaster_2.gaster_blaster_2_14]
path = "sprites/sans/gaster_blaster_2"
rotation = 252

[gaster_blaster_2.gaster_blaster_2_15]
path = "sprites/sans/gaster_blaster_2"
rotation = 270

[gaster_blaster_2.gaster_blaster_2_16]
path = "sprites/sans/gaster_blaster_2"
rotation = 288

[gaster_blaster_2.gaster_blaster_2_17]
path = "sprites/sans/gaster_blaster_2"
rotation = 306

[gaster_blaster_2.gaster_blaster_2_18]
path = "sprites/sans/gaster_blaster_2"
rotation = 324

[gaster_blaster_2.gaster_blaster_2_19]
path = "sprites/sans/gaster_blaster_2"
rotation = 342

[gaster_blaster_3.gaster_blaster_3_0]
path = "sprites/sans/gaster_blaster_3"

[gaster_blaster_3.gaster_blaster_3_1]
path = "sprites/sans/gaster_blaster_3"
rotation = 18

[gaster_blaster_3.gaster_blaster_3_2]
path = "sprites/sans/gaster_blaster_3"
rotation = 36

[gaster_blaster_3.gaster_blaster_3_3]
path = "sprites/sans/gaster_blaster_3"
rotation = 54

[gaster_blaster_3.gaster_blaster_3_4]
path = "sprites/sans/gaster_blaster_3"
rotation = 72

[gaster_blaster_3.gaster_blaster_3_5]
path = "sprites/sans/gaster_blaster_3"
rotation = 90

[gaster_blaster_3.gaster_blaster_3_6]
path = "sprites/sans/gaster_blaster_3"
rotation = 108

[gaster_blaster_3.gaster_blaster_3_7]
path = "sprites/sans/gaster_blaster_3"
rotation = 126

[gaster_blaster_3.gaster_blaster_3_8]
path = "sprites/sans/gaster_blaster_3"
rotation = 144

[gaster_blaster_3.gaster_blaster_3_9]
path = "sprites/sans/gaster_blaster_3"
rotation = 162

[gaster_blaster_3.gaster_blaster_3_10]
path = "sprites/sans/gaster_blaster_3"
rotation = 180

[gaster_blaster_3.gaster_blaster_3_11]
path = "sprites/sans/gaster_blaster_3"
rotation = 198

[gaster_blaster_3.gaster_blaster_3_12]
path = "sprites/sans/gaster_blaster_3"
rotation = 216

[gaster_blaster_3.gaster_blaster_3_13]
path = "sprites/sans/gaster_blaster_3"
rotation = 234

[gaster_blaster_3.gaster_blaster_3_14]
path = "sprites/sans/gaster_blaster_3"
rotation = 252

[gaster_blaster_3.gaster_blaster_3_15]
path = "sprites/sans/gaster_blaster_3"
rotation = 270

[gaster_blaster_3.gaster_blaster_3_16]
path = "sprites/sans/gaster_blaster_3"
rotation = 288

[gaster_blaster_3.gaster_blaster_3_17]
path = "sprites/sans/gaster_blaster_3"
rotation = 306

[gaster_blaster_3.gaster_blaster_3_18]
path = "sprites/sans/gaster_blaster_3"
rotation = 324

[gaster_blaster_3.gaster_blaster_3_19]
path = "sprites/sans/gaster_blaster_3"
rotation = 342

[gaster_blaster_4.gaster_blaster_4_0]
path = "sprites/sans/gaster_blaster_4"

[gaster_blaster_4.gaster_blaster_4_1]
path = "sprites/sans/gaster_blaster_4"
rotation = 18

[gaster_blaster_4.gaster_blaster_4_2]
path = "sprites/sans/gaster_blaster_4"
rotation = 36

[gaster_blaster_4.gaster_blaster_4_3]
path = "sprites/sans/gaster_blaster_4"
rotation = 54

[gaster_blaster_4.gaster_blaster_4_4]
path = "sprites/sans/gaster_blaster_4"
rotation = 72

[gaster_blaster_4.gaster_blaster_4_5]
path = "sprites/sans/gaster_blaster_4"
rotation = 90

[gaster_blaster_4.gaster_blaster_4_6]
path = "sprites/sans/gaster_blaster_4"
rotation = 108

[gaster_blaster_4.gaster_blaster_4_7]
path = "sprites/sans/gaster_blaster_4"
rotation = 126

[gaster_blaster_4.gaster_blaster_4_8]
path = "sprites/sans/gaster_blaster_4"
rotation = 144

[gaster_blaster_4.gaster_blaster_4_9]
path = "sprites/sans/gaster_blaster_4"
rotation = 162

[gaster_blaster_4.gaster_blaster_4_10]
path = "sprites/sans/gaster_blaster_4"
rotation = 180

[gaster_blaster_4.gaster_blaster_4_11]
path = "sprites/sans/gaster_blaster_4"
rotation = 198

[gaster_blaster_4.gaster_blaster_4_12]
path = "sprites/sans/gaster_blaster_4"
rotation = 216

[gaster_blaster_4.gaster_blaster_4_13]
path = "sprites/sans/gaster_blaster_4"
rotation = 234

[gaster_blaster_4.gaster_blaster_4_14]
path = "sprites/sans/gaster_blaster_4"
rotation = 252

[gaster_blaster_4.gaster_blaster_4_15]
path = "sprites/sans/gaster_blaster_4"
rotation = 270

[gaster_blaster_4.gaster_blaster_4_16]
path = "sprites/sans/gaster_blaster_4"
rotation = 288

[gaster_blaster_4.gaster_blaster_4_17]
path = "sprites/sans/gaster_blaster_4"
rotation = 306

[gaster_blaster_4.gaster_blaster_4_18]
path = "sprites/sans/gaster_blaster_4"
rotation = 324

[gaster_blaster_4.gaster_blaster_4_19]
path = "sprites/sans/gaster_blaster_4"
rotation = 342

[gaster_blaster_5.gaster_blaster_5_0]
path = "sprites/sans/gaster_blaster_5"

[gaster_blaster_5.gaster_blaster_5_1]
path = "sprites/sans/gaster_blaster_5"
rotation = 18

[gaster_blaster_5.gaster_blaster_5_2]
path = "sprites/sans/gaster_blaster_5"
rotation = 36

[gaster_blaster_5.gaster_blaster_5_3]
path = "sprites/sans/gaster_blaster_5"
rotation = 54

[gaster_blaster_5.gaster_blaster_5_4]
path = "sprites/sans/gaster_blaster_5"
rotation = 72

[gaster_blaster_5.gaster_blaster_5_5]
path = "sprites/sans/gaster_blaster_5"
rotation = 90

[gaster_blaster_5.gaster_blaster_5_6]
path = "sprites/sans/gaster_blaster_5"
rotation = 108

[gaster_blaster_5.gaster_blaster_5_7]
path = "sprites/sans/gaster_blaster_5"
rotation = 126

[gaster_blaster_5.gaster_blaster_5_8]
path = "sprites/sans/gaster_blaster_5"
rotation = 144

[gaster_blaster_5.gaster_blaster_5_9]
path = "sprites/sans/gaster_blaster_5"
rotation = 162

[gaster_blaster_5.gaster_blaster_5_10]
path = "sprites/sans/gaster_blaster_5"
rotation = 180

[gaster_blaster_5.gaster_blaster_5_11]
path = "sprites/sans/gaster_blaster_5"
rotation = 198

[gaster_blaster_5.gaster_blaster_5_12]
path = "sprites/sans/gaster_blaster_5"
rotation = 216

[gaster_blaster_5.gaster_blaster_5_13]
path = "sprites/sans/gaster_blaster_5"
rotation = 234

[gaster_blaster_5.gaster_blaster_5_14]
path = "sprites/sans/gaster_blaster_5"
rotation = 252

[gaster_blaster_5.gaster_blaster_5_15]
path = "sprites/sans/gaster_blaster_5"
rotation = 270

[gaster_blaster_5.gaster_blaster_5_16]
path = "sprites/sans/gaster_blaster_5"
rotation = 288

[gaster_blaster_5.gaster_blaster_5_17]
path = "sprites/sans/gaster_blaster_5"
rotation = 306

[gaster_blaster_5.gaster_blaster_5_18]
path = "sprites/sans/gaster_blaster_5"
rotation = 324

[gaster_blaster_5.gaster_blaster_5_19]
path = "sprites/sans/gaster_blaster_5"
rotation = 342

