[sprites.gaster_blaster_4_00]
path = "sprites/gaster_blaster_4"

[sprites.gaster_blaster_4_01]
path = "sprites/gaster_blaster_4"
rotation = 18

[sprites.gaster_blaster_4_02]
path = "sprites/gaster_blaster_4"
rotation = 36

[sprites.gaster_blaster_4_03]
path = "sprites/gaster_blaster_4"
rotation = 54

[sprites.gaster_blaster_4_04]
path = "sprites/gaster_blaster_4"
rotation = 72

[sprites.gaster_blaster_4_05]
path = "sprites/gaster_blaster_4"
rotation = 90

[sprites.gaster_blaster_4_06]
path = "sprites/gaster_blaster_4"
rotation = 108

[sprites.gaster_blaster_4_07]
path = "sprites/gaster_blaster_4"
rotation = 126

[sprites.gaster_blaster_4_08]
path = "sprites/gaster_blaster_4"
rotation = 144

[sprites.gaster_blaster_4_09]
path = "sprites/gaster_blaster_4"
rotation = 162

[sprites.gaster_blaster_4_10]
path = "sprites/gaster_blaster_4"
rotation = 180

[sprites.gaster_blaster_4_11]
path = "sprites/gaster_blaster_4"
rotation = 198

[sprites.gaster_blaster_4_12]
path = "sprites/gaster_blaster_4"
rotation = 216

[sprites.gaster_blaster_4_13]
path = "sprites/gaster_blaster_4"
rotation = 234

[sprites.gaster_blaster_4_14]
path = "sprites/gaster_blaster_4"
rotation = 252

[sprites.gaster_blaster_4_15]
path = "sprites/gaster_blaster_4"
rotation = 270

[sprites.gaster_blaster_4_16]
path = "sprites/gaster_blaster_4"
rotation = 288

[sprites.gaster_blaster_4_17]
path = "sprites/gaster_blaster_4"
rotation = 306

[sprites.gaster_blaster_4_18]
path = "sprites/gaster_blaster_4"
rotation = 324

[sprites.gaster_blaster_4_19]
path = "sprites/gaster_blaster_4"
rotation = 342
