[SANSGB5.gaster_blaster_5_00]
path = "sprites/sans/gaster_blaster_5"

[SANSGB5.gaster_blaster_5_01]
path = "sprites/sans/gaster_blaster_5"
rotation = 18

[SANSGB5.gaster_blaster_5_02]
path = "sprites/sans/gaster_blaster_5"
rotation = 36

[SANSGB5.gaster_blaster_5_03]
path = "sprites/sans/gaster_blaster_5"
rotation = 54

[SANSGB5.gaster_blaster_5_04]
path = "sprites/sans/gaster_blaster_5"
rotation = 72

[SANSGB5.gaster_blaster_5_05]
path = "sprites/sans/gaster_blaster_5"
rotation = 90

[SANSGB5.gaster_blaster_5_06]
path = "sprites/sans/gaster_blaster_5"
rotation = 108

[SANSGB5.gaster_blaster_5_07]
path = "sprites/sans/gaster_blaster_5"
rotation = 126

[SANSGB5.gaster_blaster_5_08]
path = "sprites/sans/gaster_blaster_5"
rotation = 144

[SANSGB5.gaster_blaster_5_09]
path = "sprites/sans/gaster_blaster_5"
rotation = 162

[SANSGB5.gaster_blaster_5_10]
path = "sprites/sans/gaster_blaster_5"
rotation = 180

[SANSGB5.gaster_blaster_5_11]
path = "sprites/sans/gaster_blaster_5"
rotation = 198

[SANSGB5.gaster_blaster_5_12]
path = "sprites/sans/gaster_blaster_5"
rotation = 216

[SANSGB5.gaster_blaster_5_13]
path = "sprites/sans/gaster_blaster_5"
rotation = 234

[SANSGB5.gaster_blaster_5_14]
path = "sprites/sans/gaster_blaster_5"
rotation = 252

[SANSGB5.gaster_blaster_5_15]
path = "sprites/sans/gaster_blaster_5"
rotation = 270

[SANSGB5.gaster_blaster_5_16]
path = "sprites/sans/gaster_blaster_5"
rotation = 288

[SANSGB5.gaster_blaster_5_17]
path = "sprites/sans/gaster_blaster_5"
rotation = 306

[SANSGB5.gaster_blaster_5_18]
path = "sprites/sans/gaster_blaster_5"
rotation = 324

[SANSGB5.gaster_blaster_5_19]
path = "sprites/sans/gaster_blaster_5"
rotation = 342
