[encoding]
format = "run_length"

[sprites.gaster_blaster_1_00]
path = "sprites/gaster_blaster_1"

[sprites.gaster_blaster_1_01]
path = "sprites/gaster_blaster_1"
rotation = 18

[sprites.gaster_blaster_1_02]
path = "sprites/gaster_blaster_1"
rotation = 36

[sprites.gaster_blaster_1_03]
path = "sprites/gaster_blaster_1"
rotation = 54

[sprites.gaster_blaster_1_04]
path = "sprites/gaster_blaster_1"
rotation = 72

[sprites.gaster_blaster_1_05]
path = "sprites/gaster_blaster_1"
rotation = 90

[sprites.gaster_blaster_1_06]
path = "sprites/gaster_blaster_1"
rotation = 108

[sprites.gaster_blaster_1_07]
path = "sprites/gaster_blaster_1"
rotation = 126

[sprites.gaster_blaster_1_08]
path = "sprites/gaster_blaster_1"
rotation = 144

[sprites.gaster_blaster_1_09]
path = "sprites/gaster_blaster_1"
rotation = 162

[sprites.gaster_blaster_1_10]
path = "sprites/gaster_blaster_1"
rotation = 180

[sprites.gaster_blaster_1_11]
path = "sprites/gaster_blaster_1"
rotation = 198

[sprites.gaster_blaster_1_12]
path = "sprites/gaster_blaster_1"
rotation = 216

[sprites.gaster_blaster_1_13]
path = "sprites/gaster_blaster_1"
rotation = 234

[sprites.gaster_blaster_1_14]
path = "sprites/gaster_blaster_1"
rotation = 252

[sprites.gaster_blaster_1_15]
path = "sprites/gaster_blaster_1"
rotation = 270

[sprites.gaster_blaster_1_16]
path = "sprites/gaster_blaster_1"
rotation = 288

[sprites.gaster_blaster_1_17]
path = "sprites/gaster_blaster_1"
rotation = 306

[sprites.gaster_blaster_1_18]
path = "sprites/gaster_blaster_1"
rotation = 324

[sprites.gaster_blaster_1_19]
path = "sprites/gaster_blaster_1"
rotation = 342
