[encoding]
format = "run_length"

[sprites.gaster_blaster_2_00]
path = "sprites/gaster_blaster_2"

[sprites.gaster_blaster_2_01]
path = "sprites/gaster_blaster_2"
rotation = 18

[sprites.gaster_blaster_2_02]
path = "sprites/gaster_blaster_2"
rotation = 36

[sprites.gaster_blaster_2_03]
path = "sprites/gaster_blaster_2"
rotation = 54

[sprites.gaster_blaster_2_04]
path = "sprites/gaster_blaster_2"
rotation = 72

[sprites.gaster_blaster_2_05]
path = "sprites/gaster_blaster_2"
rotation = 90

[sprites.gaster_blaster_2_06]
path = "sprites/gaster_blaster_2"
rotation = 108

[sprites.gaster_blaster_2_07]
path = "sprites/gaster_blaster_2"
rotation = 126

[sprites.gaster_blaster_2_08]
path = "sprites/gaster_blaster_2"
rotation = 144

[sprites.gaster_blaster_2_09]
path = "sprites/gaster_blaster_2"
rotation = 162

[sprites.gaster_blaster_2_10]
path = "sprites/gaster_blaster_2"
rotation = 180

[sprites.gaster_blaster_2_11]
path = "sprites/gaster_blaster_2"
rotation = 198

[sprites.gaster_blaster_2_12]
path = "sprites/gaster_blaster_2"
rotation = 216

[sprites.gaster_blaster_2_13]
path = "sprites/gaster_blaster_2"
rotation = 234

[sprites.gaster_blaster_2_14]
path = "sprites/gaster_blaster_2"
rotation = 252

[sprites.gaster_blaster_2_15]
path = "sprites/gaster_blaster_2"
rotation = 270

[sprites.gaster_blaster_2_16]
path = "sprites/gaster_blaster_2"
rotation = 288

[sprites.gaster_blaster_2_17]
path = "sprites/gaster_blaster_2"
rotation = 306

[sprites.gaster_blaster_2_18]
path = "sprites/gaster_blaster_2"
rotation = 324

[sprites.gaster_blaster_2_19]
path = "sprites/gaster_blaster_2"
rotation = 342
