colors = "AAAEAAgACgBAAEIAggCEAMQAxgAKAUgBiAGKAYwBzgEMApYCGAOmBDIGvgdCCFIIVgiQCpQK0ArSCtgLoAx4D4QQphAWFBgUWhScFN4UYhXkFa4YxhgCGqgb0hscHfAdZh7qHiwf+iAIIY4j/iOyJOYmKidKKUQroC6MMVo2njbOORY+EELORVJKiE2UUtZaGGNaa5xz3nsghGKMpJTmnCilaq2ste69MMZyzrTW9t4453rvvPcA+P7/"

[reserve.soul]
red = 255
green = 0
blue = 0
