[palette.reserve.soul]
red = 254
green = 0
blue = 0

[palette.reserve.white]
red = 255
green = 255
blue = 255

[palette.reserve.black]
red = 0
green = 0
blue = 0

[palette.reserve.yellow]
red = 255
green = 255
blue = 0

[palette.reserve.red]
red = 255
green = 0
blue = 0

[palette.reserve.karma]
red = 255
green = 0
blue = 255

[palette.reserve.button]
red = 255
green = 127
blue = 39

[sprites]
soul = "sprites/soul"
sans = "sprites/sans"
button_fight_icon = "sprites/button_fight_icon"
button_act_icon = "sprites/button_act_icon"
button_item_icon = "sprites/button_item_icon"
button_mercy_icon = "sprites/button_mercy_icon"
attack_meter_left = "sprites/attack_meter_left"
attack_meter_right = "sprites/attack_meter_right"
game_over = "sprites/game_over"
speach_box_left = "sprites/speach_box_left"
speach_box_right = "sprites/speach_box_right"
bone_top = "sprites/bone_end"

[sprites.bone_bottom]
path = "sprites/bone_end"
rotation = 180

[sprites.soul_090]
path = "sprites/soul"
rotation = 90

[sprites.soul_180]
path = "sprites/soul"
rotation = 180

[sprites.soul_270]
path = "sprites/soul"
rotation = 270
