[font]
height = 14

[[font.glyphs]]
index = " "
source = "comic/glyph_space"

[[font.glyphs]]
index = "!"
source = "comic/glyph_exclamation_mark"

[[font.glyphs]]
index = "'"
source = "comic/glyph_apostrophe"

[[font.glyphs]]
index = ","
source = "comic/glyph_comma"

[[font.glyphs]]
index = "."
source = "comic/glyph_period"

[[font.glyphs]]
index = "?"
source = "comic/glyph_question_mark"

[[font.glyphs]]
index = "a"
source = "comic/glyph_a"

[[font.glyphs]]
index = "b"
source = "comic/glyph_b"

[[font.glyphs]]
index = "c"
source = "comic/glyph_c"

[[font.glyphs]]
index = "d"
source = "comic/glyph_d"

[[font.glyphs]]
index = "e"
source = "comic/glyph_e"

[[font.glyphs]]
index = "f"
source = "comic/glyph_f"

[[font.glyphs]]
index = "g"
source = "comic/glyph_g"

[[font.glyphs]]
index = "h"
source = "comic/glyph_h"

[[font.glyphs]]
index = "i"
source = "comic/glyph_i"

[[font.glyphs]]
index = "j"
source = "comic/glyph_j"

[[font.glyphs]]
index = "k"
source = "comic/glyph_k"

[[font.glyphs]]
index = "l"
source = "comic/glyph_l"

[[font.glyphs]]
index = "m"
source = "comic/glyph_m"

[[font.glyphs]]
index = "n"
source = "comic/glyph_n"

[[font.glyphs]]
index = "o"
source = "comic/glyph_o"

[[font.glyphs]]
index = "p"
source = "comic/glyph_p"

[[font.glyphs]]
index = "q"
source = "comic/glyph_q"

[[font.glyphs]]
index = "r"
source = "comic/glyph_r"

[[font.glyphs]]
index = "s"
source = "comic/glyph_s"

[[font.glyphs]]
index = "t"
source = "comic/glyph_t"

[[font.glyphs]]
index = "u"
source = "comic/glyph_u"

[[font.glyphs]]
index = "v"
source = "comic/glyph_v"

[[font.glyphs]]
index = "w"
source = "comic/glyph_w"

[[font.glyphs]]
index = "x"
source = "comic/glyph_x"

[[font.glyphs]]
index = "y"
source = "comic/glyph_y"

[[font.glyphs]]
index = "z"
source = "comic/glyph_z"
