#pragma once

#include "generated/palette.h"

#define SANS_COLOR_WHITE PALETTE_RESERVE_WHITE
#define SANS_COLOR_BLACK PALETTE_RESERVE_BLACK
#define SANS_COLOR_YELLOW PALETTE_RESERVE_YELLOW
#define SANS_COLOR_RED PALETTE_RESERVE_RED
#define SANS_COLOR_BLUE PALETTE_RESERVE_BLUE
#define SANS_COLOR_KARMA PALETTE_RESERVE_KARMA
#define SANS_COLOR_BUTTON PALETTE_RESERVE_BUTTON


